import'../css/styles.css';import{GPSService}from'./gps.js';import{loadCameraPackage,updateDemoPackage,getMeta}from'./database.js';import{loadSettings,saveSettings}from'./settings.js';import{findRelevantCamera,AlertEngine,formatDistance}from'./alerts.js';import{registerServiceWorker,onNetworkChange}from'./offline.js';
const state={screen:'dashboard',moto:false,online:navigator.onLine,pos:null,cameras:[],pkg:null,settings:loadSettings(),next:null};const gps=new GPSService();let engine=new AlertEngine(state.settings);
const $=s=>document.querySelector(s);const kmh=()=>Math.round(state.pos?.speed||0);const limit=()=>state.next?.speedLimit||'—';
function render(){document.getElementById('app').innerHTML=`<div class="app"><header class="topbar"><div class="brand"><h1>Speed Guard</h1><p>Assistente offline per velocità e guida sicura.</p></div><div class="pill">${state.online?'Online':'Offline attivo'}</div></header><nav class="tabs">${tab('dashboard','Dashboard')}${tab('moto','Modalità moto')}${tab('maps','Mappe')}${tab('settings','Avvisi')}${tab('privacy','Privacy')}</nav>${dashboard()}${moto()}${maps()}${settings()}${privacy()}<div class="footer-actions"><button class="primary" id="toggleMoto">${state.moto?'Ferma modalità moto':'Avvia modalità moto'}</button></div></div>`;bind()}
function tab(id,label){return`<button class="tab ${state.screen===id?'active':''}" data-screen="${id}">${label}</button>`}
function dashboard(){return`<main class="screen ${state.screen==='dashboard'?'active':''}"><section class="grid"><div class="card speed-card"><div class="label">Velocità GPS</div><div class="speed">${kmh()}</div><div class="unit">km/h</div></div><div class="card"><div class="label">Limite attuale</div><div class="limit">${limit()}</div></div><div class="card"><div class="label">Database</div><div class="value">${state.pkg?.lastUpdated?'Aggiornato '+state.pkg.lastUpdated:'Demo locale'}</div><div class="muted">${state.cameras.length} controlli conosciuti</div></div><div class="card span"><div class="label">Prossimo controllo</div><div class="value">${state.next?`${formatDistance(state.next.distance)} - ${state.next.roadName}`:'Nessun controllo compatibile vicino'}</div><div class="muted">Filtro anti falsi avvisi: posizione, direzione e angolo frontale.</div></div></section></main>`}
function moto(){return`<main class="screen moto ${state.screen==='moto'?'active':''}"><div class="card"><div class="label">Modalità moto</div><div class="speed">${kmh()}</div><div class="unit">km/h</div><h2>Prossimo controllo: ${state.next?formatDistance(state.next.distance):'—'}</h2><div class="status-row"><span class="pill">${state.settings.vibration?'Vibrazione attiva':'Vibrazione off'}</span><span class="pill">${state.settings.voice?'Avvisi vocali attivi':'Voce off'}</span><span class="pill">${state.moto?'Background attivo*':'In pausa'}</span></div><p class="muted">* In APK Android Capacitor: usare Foreground Service per GPS persistente a schermo spento.</p></div></main>`}
function maps(){return`<main class="screen ${state.screen==='maps'?'active':''}"><div class="card"><h2>Mappe e download</h2><div class="list">${['Italia demo','Francia','Svizzera','Austria','Europa'].map((n,i)=>`<div class="download"><div><b>${n}</b><div class="muted">${i?'Non scaricato':'Scaricato · '+(state.pkg?.lastUpdated||'demo')}</div></div><button class="secondary" ${i?'disabled':''} id="updateDb">${i?'Prossimamente':'Aggiorna database'}</button></div>`).join('')}</div></div></main>`}
function settings(){return`<main class="screen ${state.screen==='settings'?'active':''}"><div class="card"><h2>Impostazioni avvisi</h2>${check('voice','Avvisi vocali')}${check('vibration','Vibrazione')}<label class="toggle">Modalità<select id="alertMode"><option value="voice-vibration">Voce + vibrazione</option><option value="voice">Solo voce</option><option value="vibration">Solo vibrazione</option><option value="off">Disattivato</option></select></label>${range('firstDistance','Primo avviso',500,2000)}${range('secondDistance','Secondo avviso',250,1000)}${range('volume','Volume voce',0,1,.1)}</div></main>`}
function privacy(){return`<main class="screen ${state.screen==='privacy'?'active':''}"><div class="card"><h2>Privacy e sicurezza</h2><p>Nessun account richiesto. La posizione viene elaborata sul dispositivo per calcolare velocità e avvisi preventivi. Non viene inviata a server esterni.</p><p>Il database è salvato offline; gli aggiornamenti scaricano solo pacchetti dati anonimi.</p><p class="warn">Speed Guard aiuta la guida consapevole: rispetta sempre limiti e condizioni della strada.</p></div></main>`}
function check(k,l){return`<label class="toggle">${l}<input type="checkbox" id="${k}" ${state.settings[k]?'checked':''}></label>`}function range(k,l,min,max,step=50){return`<label>${l}: <b>${state.settings[k]}</b><input class="range" type="range" id="${k}" min="${min}" max="${max}" step="${step}" value="${state.settings[k]}"></label>`}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen;render()});$('#toggleMoto').onclick=toggleMoto;['voice','vibration'].forEach(k=>{const e=$('#'+k);if(e)e.onchange=()=>update(k,e.checked)});['firstDistance','secondDistance','volume'].forEach(k=>{const e=$('#'+k);if(e)e.oninput=()=>update(k,Number(e.value))});const m=$('#alertMode');if(m){m.value=state.settings.alertMode;m.onchange=()=>update('alertMode',m.value)}const u=$('#updateDb');if(u)u.onclick=async()=>{state.pkg=await updateDemoPackage();state.cameras=state.pkg.items;render()}}
function update(k,v){state.settings[k]=v;saveSettings(state.settings);engine=new AlertEngine(state.settings);render()}
function toggleMoto(){state.moto=!state.moto;state.screen=state.moto?'moto':'dashboard';state.moto?gps.start():gps.stop();render()}
gps.addEventListener('position',e=>{state.pos=e.detail;state.next=findRelevantCamera(state.pos,state.cameras,state.settings);engine.process(state.pos,state.next);render()});gps.addEventListener('error',e=>console.warn(e.detail));onNetworkChange(o=>{state.online=o;render()});registerServiceWorker();loadCameraPackage().then(p=>{state.pkg=p;state.cameras=p.items;render()});getMeta().then(()=>{});render();
